apiUrl: "https://mastercraft-hunter-krb-projects.vercel.app/api/auth/minecraft/register-code"
rewardCommandsUrl: "https://mastercraft-hunter-krb-projects.vercel.app/api/rewards/commands"
pluginToken: "supersecret123"
