name: BugHunter
main: net.thecamp.bughunter.BugHunterPlugin
version: 1.0.1
api-version: "1.20"
commands:
  bughunter:
    description: Request a BugHunter registration code
    usage: /bughunter register
